config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'
  resources :books, only:[:index, :show, :edit, :create, :update]
  resources :users, only:[:index, :show, :edit, :update]
   delete 'books/:id' => 'books#destroy', as: 'destroy_book'
   get 'lists/:id/edit' => 'lists#edit', as: 'edit_list'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
has_one_attached :image
belongs_to :user

validates :title, presence: true
validates :body, presence: true, length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  
has_one_attached :profile_image
   validates :name, length: { minimum:2,maximum:20 } , uniqueness: true
   #{ minimum:2,maximum: 50 }
   validates :introduction, length: {maximum: 50}
   
  

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :authenticate_user!, except: [:top , :about]
before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
  
  def after_sign_out_path_for(resource)
    "/"
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def create
    @book_new=Book.new(book_params)
    @book_new.user_id=current_user.id
    if @book_new.save
    flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book_new.id)
    else
    @user=current_user
    @books=Book.all
    render :index
    end
  end

  def index
    @user=current_user
    @book_new=Book.new
    @books=Book.all
  end

  def show
    @book=Book.find(params[:id])
    @user=@book.user
    @book_new=Book.new
    @books=Book.new
  end

 

  def edit
   @book=Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id) 
    else
      render :edit
    end
  end

  
   def destroy
    @book=Book.find(params[:id])
    @user=current_user
    @book.destroy
    redirect_to books_path
   end

  private
  def book_params
    params.require(:book).permit(:title, :body , :user_id)
  end
  
  def is_matching_login_user
    book = Book.find(params[:id])
    unless book.user == current_user
      redirect_to books_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :is_matching_login_user, only: [:edit, :update]
  
  def index
    @users =User.all
    @user=current_user
    @book=Book.new
    @book_new=Book.new
  end
    
  def show
      @user =User.find(params[:id])
      @book=Book.new
      @books=Book.all
  end
  
  def edit
    @user=User.find(params[:id])
   user_id = params[:id].to_i
    unless user_id == current_user.id
    redirect_to user_path(current_user.id)
    end
 end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user)
    else
    render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<!-- indexからの切り取り-->

 <div class="col-md-3">
<h2>User info</h2>

  <%= image_tag user.get_profile_image(100,100) %><br>
  <table class="table">
    <tbody><tr></tr>
  <tr>
	  <th>name</th>
	  <th> <%= user.name %><br></th></tr>
	  <tr>
	  <th>introduction</th>
	  
	  <th><%= user.introduction %></th>
  </tr>
</tbody></table>

<div class="row">
  <p class="btn btn-outline-secondary btn-block">
 <%= link_to edit_user_path(user) do %>
  <i class="fas fa-user-cog text-secondary" ></i>
 <%end%></p>
  </div>


<h2 class="mt-3">New book</h2>

<%= form_with model: book do |f| %>

<div class="form-group">
<br>Title<br>
<%= f.text_field :title %></div>

<div class="form-group">
<br>Opinion<br>
<%= f.text_area :body %><br>
 </div>
 
<div class="form-group">
<%= f.submit 'Create Book' ,class:"btn btn-success"%>
</div>
<%end%>
  </div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @book do|f| %>
 <h5>Title</h5>
<%=f.text_field :title %>
<h5>Opinion</h5>
<%= f.text_area :body %><br>
  
   <%= f.submit 'Update Book' ,class: "btn btn-sm btn-success" %>
<% end %>
  

     <%= link_to "Show",book_path %>｜<%= link_to "Back",books_path %>
</div>
</div>
      </div>

app/views/books/index.html.erb
<% if @book_new.errors.any? %>
 <%= @book_new.errors.count %>errors prohibited this obj from being saved:
 <ul>
  <% @book_new.errors.full_messages.each do |message| %>
   <li><%=message%></li>
   <%end%>
 </ul>
<%end%>
<div class="container px-5 px-sm-0">
  <div class="row">
<!-- 切り取った -->
<%= render 'list', user: @user , book: @book_new %>

<div class="col-md-8 offset-md-1">
<h1>Books</h1>
  <table class="table table-hover table-inverse">
  <thead>
    <tr><th></th><th>Title</th><th>Opinion</th> <th colspan="3"></th></tr>
  </thead>
  <tbody>
      <% @books.each do |book| %>
       <tr>
    <td><%= link_to user_path(book.user.id) do %>
    <%= image_tag book.user.get_profile_image(100,100)%>
    <%end%></td>
     <td>
        <%= link_to book.title, book_path(book.id) %></td>
        <td><%= book.body %></td></tr>
        <%end%>
    </tbody>
 </table>
 </div>
</div>  
</div> 
 </div>
</div> 

app/views/books/show.html.erb
<!-- 切り取った -->
<div class="container px-5 px-sm-0">
  <div class="row">
    
<%= render 'list', user: @user , book: @book_new %>
<div class="col-md-8 offset-md-1">
<h1>Book detail</h1>

<table class="table">
   <tbody>
 
  <tr><td>
    <p>
  
          <%= image_tag @user.get_profile_image(100,100) %>
      </p>
  <%= link_to @user.name , user_path(@user.id) %>
  </td><td><%= link_to @book.title, book_path(@book.id) %></td>
  <td><%= @book.body %></td>
    <% if @book.user == current_user %>
  <td>
    <%= link_to edit_book_path(@book.id) ,class:"btn btn-sm btn-success" do %>Edit
  <% end %>
  </td>
  <td>
    <%= link_to book_path(@book.id),method: :delete, "data-confirm" => "本当に削除しますか？" ,class: "btn btn-sm btn-danger" do%>
    Destroy <% end %></td>
  </tr>
    <% end %>
</tbody></table>
    </div>
     </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to <i class="fas fa-book"></i>Bookers!
      </h1>
</h1>
  </div>
</div>

app/views/homes/top.html.erb
  <div class="row">
     <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
 <h1><b>welcome to <i class="fas fa-book"></i>Bookers !!</b></h1>
 <p>In <b><i class="fas fa-book"></i>Bookers</b>,<br><br>

you can share and exchange your opinions , inpressions , and emotions<br><br>

about various books!<br>
</p>
       <div class="btn-wrapper col-10 mx-auto">
     <p>
    <%= link_to "Log in", user_session_path ,class: "btn btn-info btn-sm btn-block mb-3 "%></p>
      <p>
<%= link_to "Sign up", new_user_registration_path ,class: "btn btn-success btn-sm btn-block sign_up" %></p>

      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <script src="https://kit.fontawesome.com/576084c6fa.js" crossorigin="anonymous"></script>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

   <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
      <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand " href="/"><span>Bookers
              </span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">


      <% if user_signed_in? %>
      <li>
         <%= link_to user_path(current_user) ,class: 'nav-link text-light' do %>
      <i class="fas fa-home"></i>Home
    <%end%>
       </li>

      <li>
         <%= link_to users_path ,class: 'nav-link text-light' do %>
        <i class="fas fa-users"></i>Users
      <%end%>
        </li>
        
      <li>
       <%= link_to books_path ,class: 'nav-link text-light' do %>
       <i class="fas fa-book-open"></i>Books
       <%end%>
        </li>
        
      <li>
        <%= link_to destroy_user_session_path, method: :delete ,class: 'nav-link text-light' do %>
        <i class="fas fa-sign-out-alt"></i>Log out
          <%end%>
      </li>
      
         <% else %>
          <li>
    <%= link_to "/" ,class: 'nav-link text-light' do %>
      <i class="fas fa-home"></i>Home
    <%end%>
       </li>

          <li>
            <%= link_to "/home/about",class: 'nav-link text-light' do %>
            <i class="fas fa-link"></i>About
        <%end%>
        </li>

      <li>
         <%= link_to new_user_registration_path ,class: 'nav-link text-light' do %>
        <i class="fas fa-user-plus"></i>Sign up
        <%end%>
      </li>

        <li>
           <%= link_to user_session_path ,class: 'nav-link text-light' do %>
         <i class="fas fa-sign-in-alt"></i>Log in
       <%end%>
      </li>

    <% end %>
     </li>
        </ul>
 </div>
    </div>
  </nav>
  </header>
  <main class="container">
   <p><%= flash[:notice] %></p>
<%= yield %>
       </main>

    <footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
  </footer>

  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>

<% if @user.errors.any? %>
  <%= @user.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  
<% end %>

<%= form_with model: @user do |f| %>
<div class="form-group">
 <label for="inputName">Name</label><br>
 <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%><br>
 </div>
 <div class="form-group">
<label for="inputImage">ProfileImage</label><br>
<%= f.file_field :profile_image, placeholder: "Image", accept: "image/*" %> <br> 
</div>

 <div class="form-group">
<label for="introduction">introduction</label><br>
<%= f.text_area :introduction, placeholder:"Introduction" %><br>
</div>
  <div class="form-group btn ">
  <%= f.submit "Update User" %>
  </div>
 </div>
</div>

      </div>
<% end %>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    
<%= render 'books/list', user: @user , book: @book_new %>

<div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
  <thead>
    <tr><th>image</th><th>name</th>
     <th colspan="3"></tr>
  </thead>
  
  <tbody>
    <% @users.each do|user| %>
    <tr><td><%= image_tag user.get_profile_image(100,100) %></td>
    <td> <%= user.name %></td>
    <td><%= link_to"Show" ,user_path(user.id) %></td></tr>
    <%end%>
 </tbody>
</table>

    </div>
      </div>
        </div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
<%= render 'books/list', user: @user , book: @book %>
<div class="col-md-8 offset-md-1">
  
<h2>Books</h2>
<table class="table table-hover table-inverse">
 <thead>
  <tr>
    <th></th>
    <th>Title</th>
   <th>Opinion</th> 
   <th colspan="3"></th>
   </tr>
   </thead>
   
      <tbody>
        <% @user.books.each do|book| %>
        <tr><td>
          <td><%= link_to user_path(book.user.id) do %>
          <%= image_tag @user.get_profile_image(100,100) %>
          <%end%></td>
        <td> <%= link_to book.title, book_path(book.id) %></td>
        <td><%= book.body %></td></tr>
        <%end%>
              </tr>
  </tbody>
</table>
    </div>
    
  </div>
</div>